# Generated by Django 5.1.6 on 2025-04-17 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundit', '0004_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItemRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='foundit.founditem')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_item_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
